name: location_beacons_android
description: "Android implementation of the location_beacons plugin."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  geolocator_android: ^4.6.0
  location_beacons_platform_interface:
    path: ../location_beacons_platform_interface

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: location_beacons
    platforms:
      android:
        package: ru.elocont.location_beacons.location_beacons
        pluginClass: LocationBeaconsPlugin
        dartPluginClass: LocationBeaconsAndroid
