clean:
	fvm flutter clean

clean_example:
	cd example; fvm flutter clean

get:
	fvm flutter pub get

get_example:
	cd example; fvm flutter pub get
	 
clean_ios:
	cd example; ./scripts/clean_ios.sh

pod_install:
	cd example/ios; pod install --repo_update
